n = input()
c = int(input())
v = int(input())
d = int(input())
sdch = d - (c*v)
print("Чек")
print(n, " - ", v, "кг", " - ", c, "руб/кг", sep='')
print("Итого: ", c * v, "руб", sep='')
print("Внесено: ", d, "руб", sep='')
print("Сдача: ", sdch, "руб", sep='')
